/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesWaterproofPaintingRouteImport } from './routes/services.waterproof-painting'
import { Route as ServicesLuxuryHomePaintingRouteImport } from './routes/services.luxury-home-painting'
import { Route as ServicesHousePaintingRouteImport } from './routes/services.house-painting'
import { Route as ServicesExteriorPaintingRouteImport } from './routes/services.exterior-painting'
import { Route as ServicesCommercialPaintingRouteImport } from './routes/services.commercial-painting'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWaterproofPaintingRoute =
  ServicesWaterproofPaintingRouteImport.update({
    id: '/waterproof-painting',
    path: '/waterproof-painting',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesLuxuryHomePaintingRoute =
  ServicesLuxuryHomePaintingRouteImport.update({
    id: '/luxury-home-painting',
    path: '/luxury-home-painting',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesHousePaintingRoute = ServicesHousePaintingRouteImport.update({
  id: '/house-painting',
  path: '/house-painting',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesExteriorPaintingRoute =
  ServicesExteriorPaintingRouteImport.update({
    id: '/exterior-painting',
    path: '/exterior-painting',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesCommercialPaintingRoute =
  ServicesCommercialPaintingRouteImport.update({
    id: '/commercial-painting',
    path: '/commercial-painting',
    getParentRoute: () => ServicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/commercial-painting': typeof ServicesCommercialPaintingRoute
  '/services/exterior-painting': typeof ServicesExteriorPaintingRoute
  '/services/house-painting': typeof ServicesHousePaintingRoute
  '/services/luxury-home-painting': typeof ServicesLuxuryHomePaintingRoute
  '/services/waterproof-painting': typeof ServicesWaterproofPaintingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/commercial-painting': typeof ServicesCommercialPaintingRoute
  '/services/exterior-painting': typeof ServicesExteriorPaintingRoute
  '/services/house-painting': typeof ServicesHousePaintingRoute
  '/services/luxury-home-painting': typeof ServicesLuxuryHomePaintingRoute
  '/services/waterproof-painting': typeof ServicesWaterproofPaintingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/reviews': typeof ReviewsRoute
  '/services': typeof ServicesRouteWithChildren
  '/services/commercial-painting': typeof ServicesCommercialPaintingRoute
  '/services/exterior-painting': typeof ServicesExteriorPaintingRoute
  '/services/house-painting': typeof ServicesHousePaintingRoute
  '/services/luxury-home-painting': typeof ServicesLuxuryHomePaintingRoute
  '/services/waterproof-painting': typeof ServicesWaterproofPaintingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/reviews'
    | '/services'
    | '/services/commercial-painting'
    | '/services/exterior-painting'
    | '/services/house-painting'
    | '/services/luxury-home-painting'
    | '/services/waterproof-painting'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/reviews'
    | '/services'
    | '/services/commercial-painting'
    | '/services/exterior-painting'
    | '/services/house-painting'
    | '/services/luxury-home-painting'
    | '/services/waterproof-painting'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/reviews'
    | '/services'
    | '/services/commercial-painting'
    | '/services/exterior-painting'
    | '/services/house-painting'
    | '/services/luxury-home-painting'
    | '/services/waterproof-painting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  ReviewsRoute: typeof ReviewsRoute
  ServicesRoute: typeof ServicesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/waterproof-painting': {
      id: '/services/waterproof-painting'
      path: '/waterproof-painting'
      fullPath: '/services/waterproof-painting'
      preLoaderRoute: typeof ServicesWaterproofPaintingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/luxury-home-painting': {
      id: '/services/luxury-home-painting'
      path: '/luxury-home-painting'
      fullPath: '/services/luxury-home-painting'
      preLoaderRoute: typeof ServicesLuxuryHomePaintingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/house-painting': {
      id: '/services/house-painting'
      path: '/house-painting'
      fullPath: '/services/house-painting'
      preLoaderRoute: typeof ServicesHousePaintingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/exterior-painting': {
      id: '/services/exterior-painting'
      path: '/exterior-painting'
      fullPath: '/services/exterior-painting'
      preLoaderRoute: typeof ServicesExteriorPaintingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/commercial-painting': {
      id: '/services/commercial-painting'
      path: '/commercial-painting'
      fullPath: '/services/commercial-painting'
      preLoaderRoute: typeof ServicesCommercialPaintingRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesCommercialPaintingRoute: typeof ServicesCommercialPaintingRoute
  ServicesExteriorPaintingRoute: typeof ServicesExteriorPaintingRoute
  ServicesHousePaintingRoute: typeof ServicesHousePaintingRoute
  ServicesLuxuryHomePaintingRoute: typeof ServicesLuxuryHomePaintingRoute
  ServicesWaterproofPaintingRoute: typeof ServicesWaterproofPaintingRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesCommercialPaintingRoute: ServicesCommercialPaintingRoute,
  ServicesExteriorPaintingRoute: ServicesExteriorPaintingRoute,
  ServicesHousePaintingRoute: ServicesHousePaintingRoute,
  ServicesLuxuryHomePaintingRoute: ServicesLuxuryHomePaintingRoute,
  ServicesWaterproofPaintingRoute: ServicesWaterproofPaintingRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  ReviewsRoute: ReviewsRoute,
  ServicesRoute: ServicesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
